@startuml
'https://plantuml.com/class-diagram


class Product{
_name: string
_productId: string
_price: floet
_quantity: int
Product(name, id, price, quantity)
TotalCost(): float
}
class Customer {
_name: string
_address: Address
Customer( name : string, address:Address)
FromUS(Address) : bool
}
class Address {
_street: string
_city: string
_state: string
_country: string

Address( street, city, state, country)
FromUS(): bool
DisplayAddress(): string
}
class Order {
_productList: List<Product>
_customer: Customer
Order(productlist, customer)
CalculateTotal(): float
PackingLabel(): string
ShippingLabel(): string
}
@enduml